apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.type }}type: {{ .Values.service.type }}{{- end }}
  {{- if .Values.service.spec }}{{ .Values.service.spec | toYaml | nindent 2 }}{{- end }}
  ports:
    - name: https-coturn
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
