apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reticulum.fullname" . }}
  labels:
    {{- include "reticulum.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  minReadySeconds: 15
  strategy:
    {{- if .Values.autoscaling.enabled }}
    {{- include "reticulum.autoscaling.strategy" . | nindent 4 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "reticulum.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reticulum.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reticulum.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: 
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 9100
          livenessProbe:
            httpGet:
              path: /health
              port: 4001
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 30
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /?skipadmin
              port: 4001
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 5
            failureThreshold: 100
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: 
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          env: 
            {{- toYaml .Values.env | nindent 12 }}

        {{- if .Values.sidecar.enabled }}
        - name: {{ .Values.sidecar.name }}
          image: {{ .Values.sidecar.image }}
          ports:
            {{ toYaml .Values.sidecar.ports | nindent 12 }}
          env: 
            {{ toYaml .Values.sidecar.env | nindent 12 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
