{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}

{{- end }}