apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}
