{{- if .Values.global.aws.efs.enabled}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-efs-storage-class
provisioner: efs.csi.aws.com
{{- if .Values.global.aws.efs.isDynamicProvisioning}}
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.global.aws.efs.fileSystemId }}
  directoryPerms: "700"
{{- end}}
{{- end}}